# OpenTelemery collector config
#
# - extensions: health_check, zpages
# - receiver: filelog
# - processor:
#   - batch_memory limits
#   - custom attributes (metadata), resources
# - exporter: debug
extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  zpages:
    endpoint: "0.0.0.0:55679"

receivers:
  filelog:
    include: [/var/log/myapp/test.log]
    start_at: end
    operators:
    - type: regex_parser
      regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}) (?P<severity>[A-Z]*) (?P<msg>.*)$'
      timestamp:
        parse_from: attributes.timestamp
        layout: '%Y-%m-%dT%H:%M:%S'
      severity:
        parse_from: attributes.severity
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  memory_limiter:
    check_interval: 2s
    limit_percentage: 75
    spike_limit_percentage: 15

  attributes/add_metadata:
    actions:
      - key: deployment.environment
        action: insert
        value: production
      - key: service.version
        action: upsert
        value: 1.2.3
  resource/add_service_info:
    attributes:
      - key: service.name
        action: upsert
        value: "billing-api"
      - key: service.namespace
        action: upsert
        value: "payments"
      - key: cloud.region
        action: upsert
        value: "us-west-2"

exporters:
  debug:
    verbosity: detailed # basic, normal, detailed

service:
  # Debug OpenTelemetry internals
  # telemetry:
  #   logs:
  #     level: debug
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource/add_service_info, attributes/add_metadata]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [resource/add_service_info, attributes/add_metadata]
      exporters: [debug]
    logs:
      receivers: [filelog]
      processors: [resource/add_service_info, attributes/add_metadata]
      exporters: [debug]
